services:
  - type: web
    name: shopping-cart-backend
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    region: singapore
    envVars:
      - key: SPRING_DATA_MONGODB_URI_PRODUCT
        sync: false
      - key: SPRING_DATA_MONGODB_URI_USER
        sync: false
      - key: SPRING_DATA_MONGODB_URI_CART
        sync: false
      - key: SPRING_DATA_MONGODB_URI_ORDER
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: FRONTEND_URL
        value: https://placeholder.vercel.app
